### ISSUE TITLE
Download the iso-profiles repo without git 

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#17]
This would allow for fewer dependencies.

**Comment by oberon-manjaro** [comment]
A stable branch and a package of iso-profiles will be available after 17.0 release. Then you can just install the package.

**Comment by Chrysostomus** [comment]
But aren't the repo the repo packages always horribly lagging behind? Then again, that might gain some stability to the process...

**Comment by oberon-manjaro** [comment]
We'll just have to pay attention and update the profiles package more regularly. We need to cultivate a proper stable branch there - was not so essential until now, since there was no real need for it.
A proper Stable branch will also have the advantage that you won't clone the experimental changes that happen all the time ...

**Comment by Chrysostomus** [comment]
That seems like a good idea

**Comment by oberon-manjaro** [comment]
We can simply offer both options and install **git** only when needed - I'm currently coding that :)

**Comment by oberon-manjaro** [comment]
Please review and test https://github.com/Chrysostomus/aif-dev/commit/5778c228a763b898ad45aec85c9d19bd94281230

**Comment by oberon-manjaro** [comment]
I have updated the **iso-profiles** packages now. So at the moment git and pkg are identical.
