### ISSUE TITLE
improve logging / debugging

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#19]
For troubleshooting it will be important to be able to trance back which steps were taking during installation, which packages selected and downloaded.
It would be great to write some kind of a complete logfile to the target install.
Also I haven't really figured out what the best way is to debug during installation. How do you do that currently @Chrysostomus ?

**Comment by Chrysostomus** [comment]
The original script captures most errors and then showed them via dialog window. This makes debugging very frustrating due to the lack of context. That's why I made some parts to just print their errors to stdout. This has a drawback though: without tmux, you can't scroll up to see the errors if there are many. 

I would like that we print everything to terminal and tee it to single log file. It is significantly less pretty though.

**Comment by oberon-manjaro** [comment]
Sounds ok for me. It would even be possible to include a -d switch for stdout and else write to file only. In any case I think it would be good - at least for the rough dev phase - to dump the file to target install at the end so we have something to ask people for. Ideally we should see there even the information about the actual settings that have been selected.
Quit a bit of extra work likely - but it might payoff in the end, what do you think?

**Comment by Chrysostomus** [comment]
I wonder if there could be some shortcut... Like Could we just tee the whole script instead of adding tee everywhere inside it? It could hopefully also capture the dialog windows used (though I have no idea how we could display that... But it is just stuff printed to console/stdout AFAIK)

**Comment by Chrysostomus** [comment]
The script creates quite a few files in /tmp. I usually check those when debugging.

**Comment by Chrysostomus** [comment]
Piping the whole script into tee breaks dialog, so we cannot do that. Apparently we have to insert it into the script.

**Comment by oberon-manjaro** [comment]
Would it maybe be useful at least to move the existing log instead of [wiping it](https://github.com/Chrysostomus/aif-dev/blob/master/manjaro-architect#L283)?
Just something like ``mv /tmp/.errlog /tmp/.errlog0`` ?

**Comment by Chrysostomus** [comment]
Yes, definitely. Maybe it would be easiest to modify the check_for_error so it would begin with 

     cat /tmp/.errlog >> /tmp/.errlog0

Then we would get a full errorlog. The problem with this is that it is very difficult to know what command the error belongs to... Basestrap commands generate some pretty bad looking but totally harmless errors because some install scripts fail in basestrap situation. 

Having combined errlog is the first step. We then also need something to sort the log. Some kind of identifier for commands, which would be >> to errlog0 before the check for error if there is a error. 

Before the commands that we check errors for, set operation variable, and add 

      echo $operation >> /tmp/.errlog0 

At the beginning of check_for_error? 

That way we get a full list of all errors we are interested in, sorted by operation names, while check_for_error still works as intended?

**Comment by Chrysostomus** [comment]
Ah, I see you meant something else...

**Comment by oberon-manjaro** [comment]
Did I? :laughing: Not sure. In any case that ^ sounds good!!

**Comment by Chrysostomus** [comment]
My best ideas come from misunderstanding other people and imagining someone else has already come up with something :D

**Comment by oberon-manjaro** [comment]
I've proposed something - sorry, only saw your self-assignement just now ;)
For full logging if we want that in some cases it should work to use `` 2>&1 | tee > <some/dedicated/logfile>``, yes. If you want to do the whole thing differently, just let me know :)

**Comment by Chrysostomus** [comment]
No worries, I don't really care who does it.
