### ISSUE TITLE
PCIe Bus Error

### ISSUE THREAD

**Issue by johanneskopf** [Chrysostomus/aif-dev#221]
When booting into Manjaro Architect after some time it shows the following error about every 16 seconds:

```
pcieport 0000:00:1c:0: PCIe Bus Error: serverity=Corrected, type=Data Link Layer, id=00e0(Transmitter ID)
pcieport 0000:00:1c:0: device [8086:a110] error status/mask=00001000/0000200
pcieport 0000:00:1c:0: [12] Replay Timer Timeout

```
This always discards my current unfinished command (eg. in gparted). So I have to type it again and confirm it before this message appears again.

Is this really an error (as it states Corrected)? And can this output somehow be prevented?

**Comment by Chrysostomus** [comment]
This is a problem with live media and not the installer. You could try running the installer in another TTY in case the error gets printed out only in TTY1. If you are using a live iso, its probably not worth fixing it there.

This kind of problem can be sometimes caused by (possibly nvidia) graphics drivers interacting with TLP or something.
