### ISSUE TITLE
Cancel option does not work in many menus 

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#47]
https://forum.manjaro.org/t/unstable-manjaro-architect-beta-testing/16010/341

**Comment by Chrysostomus** [comment]
We just need to add a check for empty string after the dialog calls and it should be okay.

**Comment by oberon-manjaro** [comment]
I can't find that in the topic. Where exactly is the problem? I didn't run into that sofar.
A place that is behaving strangely for me is when after "Install Base Packages" the next one is auto-highlighted: "Install Bootloader". And when I confirm that, instead of opening the Bootloader dialog it throws be back to the Main Menu. It only happens when I arrive there for the first time as described above. After that everything is back to normal.
I will try if un-nesting the bootloader functions helps.
It's also a general question: Should we un-nest generally? Is there any benefit in having functions nested since the libraries are sourced when the app is launched anyway?

**Comment by Chrysostomus** [comment]
Unnesting would make navigating some submenus easier.

**Comment by oberon-manjaro** [comment]
This is fixed I think.
