### ISSUE TITLE
Base installation -> system-d -> Advanced selection

### ISSUE THREAD

**Issue by fhdk** [Chrysostomus/aif-dev#8]
Using defaults presented including linux49 kernel.

After installation has processed the selections - installer throws an error as if no kernel is selected

```
Message is Error: Invalid argument.
Please chose one of the available kernels:
* linux310
* linux312
* linux316
* linux318
* linux41
* linux410
* linux44
* linux48
* linux49
* linux-rt-lts-manjaro
* linux-rt-manjaro
```

**Comment by Chrysostomus** [comment]
I can replace the issue. Something nonkernel gets passed to mhwd. I'll rework the base installation.

**Comment by Chrysostomus** [comment]
The problem arises from the fact that kernels are filtered for mhwd-kernel with 

      $(cat ${PACKAGES} | xargs -n1 | grep "^linux" | xargs)

There is probably something else in the list that  starts with linux. I think I will modify it so that the list of offered kernels is generated with `mhwd-kernel -l`. The I can just grep ${PACKAGES} with that list. Added bonus: more kernels and no maintenance needed for this part in the future.
