### ISSUE TITLE
Menu order is illogical

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#93]
We have "configure base" before "install graphical interface, even though latter has options that effect user creation. 

We also have "set keymap" as a suggested option before installing xorg. It fails with this error when run in that order: https://forum.manjaro.org/t/unstable-manjaro-architect-beta-testing/16010/650

Suggested solution: since we have already drivers menu, we could move "install manjaro desktop" there, and "keymap" to "configure base"

Like this:

```
 1  Prepare Installation           >  
 2  Install System                    >
      -    1  Configure Installer Mirrorlist  >    
      -    2  Refresh Pacman Keys     
      -    3  Install Base Packages
      -    4  Install Manjaro Desktop        >    
      -    5  Install drivers                        >  
      -    6  Install Bootloader
      -    7  Back      
 3  Configure Base                 >    
      -    1  Generate FSTAB         
      -    2  Set Hostname
      -    3  Set System Locale
      -    4  Set Keymap
      -    5  Set Timezone and Clock 
      -    6  Set Root Password      
      -    7  Add New User(s)       
 4  Review Configuration Files  
 5  Advanced Installation       >  
 6  Done  
```

**Comment by oberon-manjaro** [comment]
Looks good!

**Comment by Chrysostomus** [comment]
Implemented in the local branch, I'll push it soon

**Comment by sueridgepipe** [comment]
My post about this was buried in the beta testing thread, better to repeat it here and get some feedback.

Even with the changes above I really think a completely different, workflow structured menu design is required, and the more I use manjaro-architect the more convinced I am.

https://forum.manjaro.org/t/unstable-manjaro-architect-beta-testing/16010/663

Done A LOT of installations over the last few weeks and IMO the workflow just doesn't work, to the point where I think this menu structure is quite broken. Instead of just complaining I've come up with an alternative menu structure for consideration.

All the functionality is there, these components work well, the installation just needs to flow better and feel more intuitive, **more Manjaro like**. For some install scenarios I find myself jumping all over the menu structure, it is very easy to lose track of what you have done and what you still need to do.  The Advanced menu catch all make less sense the more I use it.

The idea is that there are **three different self contained installation system options** offered, instead of the disjointed, isolated installation tasks currently presented

Main Menu
├─ Prepare Installation
├─ Install Manjaro NET System
├─ Install Manjaro Desktop System
├─ Install Custom Manjaro System
└─ Exit Manjaro Architect

Each of these will contain all steps required to complete an install this type of Manjaro system, and still provide the overall freedom to create any type of system you wish. There will be menu item duplication, which I am sure can be coded in a modular fashion, but as an installer I think this makes more sense and flows MUCH better.

Main Menu
├── Prepare Installation
│   ├── Set Virtual Console
│   ├── List Devices (optional)
│   ├── Partition Disk
│   ├── Luks Encryption (optional)
│   ├── Logical Volume Management (optional)
│   ├── Mount Partitions
│   ├── Configure Installer Mirrorlist
│   └── Refresh Pacman Keys
├── Install Manjaro NET System
│   ├── Install Base Packages
│   ├──── [ ] Select Init System
│   ├──── [ ] Select Linux Packages
│   ├──── [ ] Select Additional Kernel Modules
│   ├── Install Network Driver(s) *
│   ├── Install Bootloader
│   ├── Configure Base System 
│   ├──── Generate FSTAB
│   ├──── Set Hostname
│   ├──── Set System Locale
│   ├──── Set Timezone and Clock
│   ├──── Set Root Password
│   ├──── Create New Users(s)
│   ├────── [ ] Select Shell
│   ├──── Run Mkinitcpio
│   ├── Install Custom Packages
│   ├── Security and systemd Tweaks
│   └── Review System Configuration Files
├── Install Manjaro Desktop System
│   ├── Install Base Packages
│   ├──── [ ] Select Init System
│   ├──── [ ] Select Linux Packages
│   ├──── [ ] Select Additional Kernel Modules
│   ├── Install Network Driver(s) *
│   ├── Install Bootloader
│   ├── Configure Base System 
│   ├──── Generate FSTAB
│   ├──── Set Hostname
│   ├──── Set System Locale
│   ├──── Set Timezone and Clock
│   ├──── Set Root Password
│   ├──── Create New Users(s)
│   ├────── [ ] Select Shell
│   ├──── Run Mkinitcpio
│   ├── Install Display Driver
│   ├── Set Keyboard Layout
│   ├── Install Manjaro Desktop
│   ├──── [ ] Select Manjaro Edition
│   ├──── [ ] Select Package Version
│   ├──── [ ] Select Manjaro Common Packages
│   ├── Install Custom Packages
│   ├── Security and systemd Tweaks
│   └── Review System Configuration Files
├── Install Custom Manjaro System
│   ├── Install Base Packages
│   ├──── [ ] Select Init System
│   ├──── [ ] Select Linux Packages
│   ├──── [ ] Select Additional Kernel Modules
│   ├── Install Network Driver(s) *
│   ├── Install Bootloader
│   ├── Configure Base System 
│   ├──── Generate FSTAB
│   ├──── Set Hostname
│   ├──── Set System Locale
│   ├──── Set Timezone and Clock
│   ├──── Set Root Password
│   ├──── Create New Users(s)
│   ├────── [ ] Select Shell
│   ├──── Run Mkinitcpio
│   ├── Install Graphical Environment
│   ├──── Install Display Driver
│   ├──── Set Keyboard Layout
│   ├──── Install Display Server
│   ├──── Install Desktop Environment(s)
│   ├────── [ ] Select Unconfigured Desktop Environment(s)
│   ├──── Install Display Manager
│   ├── Install Additional Packages
│   ├──── Install Network Connection Manager
│   ├──── Install CUPS / Printer Packages
│   ├──── Install Sound Driver(s)
│   ├──── Install Codecs
│   ├──── Install Accessibility Packages
│   ├──── Install Manjaro Common Packages
│   ├────── [ ] Select Manjaro Common Packages
│   ├── Install Custom Packages
│   ├── Security and systemd Tweaks
│   └── Review System Configuration Files
└── Exit Manjaro Architect

The only thing missing from the above menu structure is the Manjaro development DE profiles option, which is currently in Advanced section, but should be incorporated back into this section somewhere instead.

│   ├── Install Manjaro Desktop
│   ├──── [ ] Select Manjaro Edition
│   ├──── [ ] Select Package Version
│   ├──── [ ] Select Manjaro Common Packages

Hopefully others feel similarly because the more installs I do the more I am convinced the current setup just doesn't work. At best the current structure is clunky and cumbersome, and at worst it can be unintuitive and confusing, leading to installation omissions and errors.

Thoughts?

**Comment by oberon-manjaro** [comment]
Wow! I like :nerd_face:

**Comment by oberon-manjaro** [comment]
@Chrysostomus do you spot anything that makes this a problem? I agree this is a very intuitive structure.

**Comment by sueridgepipe** [comment]
It was not obvious with the current menu the types of systems that manjaro-architect could support.  It relied on the user making sense of the disparate install tasks first and manually piecing a system together.

This new menu layout makes it explicit and walks the user through the process for each system type, step by step, or menu by menu.

**Comment by sueridgepipe** [comment]
It also gets rid of the simple vs advanced concept, which I never really liked in the first place.

No new functionality needs to be developed either, it is all there, just needs to be re-arranged to represent the installation workflow from a user's perspective.

**Comment by oberon-manjaro** [comment]
I am less and less convinced about the need to offer the access to dev profiles. In the **iso-profiles** repo we've now created a stable branch. We should just see that profiles packages get updated with fixes and necessary adjustments. To use master branch of iso-profiles for user installation is really not useful at every given moment and for every profile. It might even be good to have some kind of control over that via packaging.

**Comment by Chrysostomus** [comment]
I suggest we still keep option for dev profiles, but only through cli options. It is useful for testing, but not for final product. 

I'm fine with the basic idea, maybe a few tweaks here and there, but the the structure seems clear and useful.

**Comment by oberon-manjaro** [comment]
CLI option, you mean with a flag like ``manjaro-architect -g`` or so? Why not!?

**Comment by sueridgepipe** [comment]
Maybe if you launch using...

`
sudo manjaro-architect --dev
`

Then you get an additional choice for manjaro desktop install...

│ ├── Install Manjaro Desktop
│ ├──── [ ] Select Manjaro Edition
│ ├──── [ ] Select Package Version
**│ ├──── [ ] Select Package Profile**
│ ├──── [ ] Select Manjaro Common Packages

**Comment by Chrysostomus** [comment]
Yeah, like that. Currently some parts already monitor check for /tmp/.developmentprofiles (or something like that). Just touch it if flag is used and rm it on exit if it exists.

**Comment by sueridgepipe** [comment]
Do you want to pencil in btrfs volume management into Prepare Installation menu, for possible inclusions and implementation down the road?

**Comment by Chrysostomus** [comment]
Not sure if I understand the question, but I would implement btrfs subvolume creation as a part of the partition mounting like it was in previous installer. If format to btrfs, you get option to create and mount subvolumes.

**Comment by sueridgepipe** [comment]
Yeah, that is what I meant, didn't realise it would be part of the process of mounting and formatting a btrfs partition.

**Comment by Chrysostomus** [comment]
Alternatively we could make menu similar to lvm menu. That would make it easier to implement raid functions, but would be more complicated for basic usage, and orders of magnitude more complex to code

**Comment by sueridgepipe** [comment]
> I'm fine with the basic idea, maybe a few tweaks here and there, but the the structure seems clear and useful.

What would you change and why?

**Comment by Chrysostomus** [comment]
Use the combined drivers menu instead of separate display and network drivers, like it is currently in the git version. Feels simpler. 

Install graphical environment before configuring the base in "Install Manjaro Desktop System", because doing this in the wrong order causes issues. Better yet, combine desktop and base installation under this section, because (a) it reduces margin of error (b) separating base from this doesn't make any sense in this section. The user has already decided he wants graphical environment! 

Move keyboard layout setting to configuration. This can be done only after Xorg is installed.

**Comment by sueridgepipe** [comment]
These are good ideas, like this?

├── Install Manjaro Desktop System
│ ├── Install Manjaro Desktop
│ ├──── [ ] Select Init System
│ ├──── [ ] Select Linux Packages
│ ├──── [ ] Select Additional Kernel Modules
│ ├──── [ ] Select Display Driver
│ ├──── [ ] Select Manjaro Edition
│ ├──── [ ] Select Package Version
│ ├──── [ ] Select Manjaro Common Packages
│ ├── Install Bootloader
│ ├── Configure Manjaro Desktop
│ ├──── Generate FSTAB
│ ├──── Set Hostname
│ ├──── Set System Locale
│ ├──── Set Timezone and Clock
│ ├──── Set Keyboard Layout
│ ├──── Set Root Password
│ ├──── Create New Users(s)
│ ├────── [ ] Select Shell
│ ├──── Install Network Driver(s) *
│ ├──── Run Mkinitcpio
│ ├── Install Custom Packages
│ ├── Security and systemd Tweaks
│ └── Review System Configuration Files

What about the Custom Manjaro System?  Combine the Base and Graphical Environment Install too, like this...

├── Install Custom Manjaro System
│ ├── Install Custom Manjaro
│ ├──── [ ] Select Init System
│ ├──── [ ] Select Linux Packages
│ ├──── [ ] Select Additional Kernel Modules
│ ├──── [ ] Select Display Driver
│ ├──── [ ] Select Display Server
│ ├──── [ ] Select Unconfigured Desktop Environment(s)
│ ├──── [ ] Select Manjaro Common Packages
│ └──── [ ] Select Display Manager
├── Install Bootloader
│ ├── Configure Custom Manjaro
│ ├──── Generate FSTAB
│ ├──── Set Hostname
│ ├──── Set System Locale
│ ├──── Set Timezone and Clock
│ ├──── Set Keyboard Layout
│ ├──── Set Root Password
│ ├──── Create New Users(s)
│ ├────── [ ] Select Shell
│ ├──── Install Network Driver(s) *
│ ├──── Run Mkinitcpio
│ ├── Install Additional Packages
│ ├──── Install Network Connection Manager
│ ├──── Install CUPS / Printer Packages
│ ├──── Install Sound Driver(s)
│ ├──── Install Codecs
│ ├──── Install Accessibility Packages
│ ├──── Install Additional Unconfigured Desktop Environments(s)
│ ├────── [ ] Select Unconfigured Desktop Environment(s)
│ ├── Install Custom Packages
│ ├── Security and systemd Tweaks
│ └── Review System Configuration Files
 
Do we want to allow additional DEs to be installed as a separate item, instead of embedded in a combined Base + Graphic Environment install.  Penciled in, not sure if it belongs though.

> Use the combined drivers menu instead of separate display and network drivers, like it is currently in the git version. Feels simpler.

I disagree, you are looking at the solution from a developer's perspective, not from a user's perspective.  We need to think of this structure in terms of overall workflow, even if this means abstracting and re-using the underlying driver install implementation.

**Comment by oberon-manjaro** [comment]
What do you mean @sueridgepipe ?
Current git state looks like this:
```
install_drivers_menu() {
    local PARENT="$FUNCNAME"
    declare -i loopmenu=1
    while ((loopmenu)); do
        submenu 5
        DIALOG " _InstDrvTitle " --default-item ${HIGHLIGHT_SUB} --menu "$_InstDrvBody" 0 0 5 \
          "1" "$_InstFree" \
          "2" "$_InstProp" \
          "3" "$_InstGrMenuDD|>" \
          "4" "$_InstNWDrv|>" \
          "5" "$_Back" 2>${ANSWER}
        HIGHLIGHT_SUB=$(cat ${ANSWER})

        case $(cat ${ANSWER}) in
            "1") arch_chroot "mhwd -a pci free 0300"
                ;;
            "2") arch_chroot "mhwd -a pci nonfree 0300"
                ;;
            "3") setup_graphics_card
                ;;
            "4") setup_network_drivers
                ;;
            *) loopmenu=0
                return 0
                ;;
        esac
    done
}
```
What do you think would be an end-user's confusion with this?
video-driver and network are in fact separate entries. They are just in one category, which I think is good.

**Comment by sueridgepipe** [comment]
Install display driver is a part of installing the graphical environment, and installing network driver is a part of configuring the installation.  Just because they are both drivers doesn't necessarily mean they belong together in the installation workflow.

Its 2am and I'm tired, the current git changes stood out like bulldog knackers when I tried it briefly, but maybe I'm a little grumpy.  My main point is to think about the menu structure in terms of logical install workflow, not simply grouping technically "like" actions, which is sometimes difficult for developers really close to the implementation details.

Not a big deal, just something to think about.

For instance it makes more sense logically to structure display driver selection this way instead of a menu, and move Network driver to a separate menu item.  It could be the next step if you wish.

├─ Install Display Driver
│ ├─ [ ] Detect and Install Free Display Driver
│ ├─ [ ] Detect and Install Non-Free Display Driver
│ ├─ [ ] Manually Select Display Driver
│ ├─── [ ] video-intel
│ ├─── [ ] video-nvidia
│ ├─── [ ] video-nouveau
│ ├─── [ ] video-hybrid-intel-nvidia-bumblebee
│ ├─── [ ] video-hybrid-intel-nouveau-bumblebee
│ ├─── [ ] video-vesa

**Comment by Chrysostomus** [comment]
You make a good point about driver installation. My reason for combining them is this: the first two items should automatically take care of both in one step, like other installers do. But we can separate them too.

**Comment by Chrysostomus** [comment]
I don't think there is technical need to combine base and desktop installation in unconfigured desktops section. They are unconfigured, so there is no need to jump through extra coding hoops to make their configuration work. 

But how about merging unconfigured desktops and and net edition installation? Configured desktops section is essentially just post installation stuff after base. User could just quit before installing graphical interface to get the base.

**Comment by sueridgepipe** [comment]
What works and what doesn't work from a logical workflow perspective only really becomes apparent when using it.  There have been ideas I thought were really good throughout development, but when I got around to using it extensively it became apparent some just didn't work.  Combining drivers is one I thought was good when you proposed it, but using it over and over again, this solution just didn't work for me.  Others may disagree and healthy discussion is good, it will lead to a better solution in the long run.

I agree with you, Install Custom Manjaro System should be as fine grained as possible to give the user the maximum amount of flexibility and control.  I combined base and graphical install to see how it looked, but as you point out it doesn't make a lot of sense.

Personally I like keeping the Net System and Custom Manjaro System options separate.  You could install a Net System by simply installing and configuring base packages from the Custom Manaro System menus, but for users that want a Net System I think having an explicit system menu option front and centre is more intuitive, rather than requiring them to have to work this out for themselves.

Having two install paths to the same system outcome, one explicit and one possible through an "installation sandpit", is not necessarily a bad thing.  Makes the installer more intuitive **and** more flexible at the same time.  Some users will appreciate the streamlined explicit option, whilst others will appreciate the enormous amount of control offered though a fine grained custom system install.  

Hopefully this leads to more happy users.

:smile:

**Comment by oberon-manjaro** [comment]
Thank you @sueridgepipe for all your profound input, for your concern and the incredible amount of time and energy you are investing in this project! It is a gift to have someone like you as a tester and I am sure you will be holding the record for the person who did the most installs with the architect for at least a very long time - most likely no one will ever catch  up with you now, anyway... :laughing:

**Comment by oberon-manjaro** [comment]
I agree that since we have the luxury now in the structure of the code that there is no need for any kind of a consecutive order of menu entries, repetition will not hurt. It will just be like sorting the content in different ways, depending on what the user is looking for.
I am not complelety happy with the tag NET install even though it is what people are currently used to and what they will be asking for. But since now all the architect's installs are in fact 'net'-installs I'd prefer we establish a new name. Base install seems to make most sense for me. What do you guys think?

**Comment by sueridgepipe** [comment]
Is there a catch-all term for a GUI-less system?  Whilst NET is not the correct term, most people seem to associate this with a GUI-less system, right or wrong.  Headless?  Nah, that's just a monitor less system.

What about Manjaro CLI System, or is that too obtuse?

Main Menu
├─ Prepare Installation
├─ Install Manjaro CLI System
├─ Install Manjaro Desktop System
├─ Install Custom Manjaro System
└─ Exit Manjaro Net Installer

No probs with the testing stuff Im doing, I honestly didn't expect to become this invested and immersed when I started out, just wanted to assist in some way.  The more I use it the more I keep thinking how good it could be if it is done right.  I don't develop, but I have a brain that works a bit (although sometimes it doesn't shutoff :roll_eyes: ), and having devs that don't simply ignore the input of a "pleb user" helps a lot too :wink: .

Potentially manjaro-architect could eventually be re-badged down the track as the replacement Manjaro Net Installer.  That would be very cool, and has the potential to be a standout feature of this distro.

**Comment by Chrysostomus** [comment]
"Base" makes most sense to me. "barebones" could also work

**Comment by sueridgepipe** [comment]
If I understand correctly, "Base" is a technical term used to describe the basic package profile used by pacstrap, it is really an Arch term, will this term make sense to new users?  I understand Base is technically accurate, but wearning my user's hat I don't think it provides enough clarity for non technical users.  This is an installer so we should assume most users will be new to Manjaro, and they may not associate Base with GUI-less.

"Barebones" is too vague I think, it could be mean anything.  You could also describe a minimal package Manjaro Desktop System as barebones too, relative to a full package Manjaro Desktop System.

"CLI" is a more universally understood acronym, and "CLI System" implies a functional GUI-less system.

If not CLI is there another term that better describes a GUI-less system?

**Comment by sueridgepipe** [comment]
Is the 0.8 menu structure the final menu structure?

If anything it is even more illogical, unintuitive, poorly designed and unusable than it was in 0.7.  A significant step in the wrong direction IMO, but no point in me repeating myself.

**Comment by oberon-manjaro** [comment]
Nothing is final and there is still a lively discussion about options also possibly with a completely dynamic approach - all over this repo... At some point you just need to release a certain state as a snapshot of development or changes will just go on forever without an opportunity for components to stabilize and settle down. Every structural change opens more doors for mistakes, typos, makes issues apparent you weren't aware of before or that suddenly become an issue in a different context.
So it just needs to happen in a more or less sane pace. We were already rushing things a lot lately. Time to breath, think, reorganize, bugfind/bugfix...! :wink: 
Rest assured that your input is and has always been highly valued, appreciated, respected and heard and I am sure that many of your suggestions will find their way into the code sooner or later. It just can't happen everything right now and immediately. It's a process of development...
